export const getSeedBranches = () => [
  {
    name: 'Computer Science and Information Technology',
    code: 'CS',
    description: 'GATE CS syllabus covering Core Systems, Algorithms, Theory of Computation, and Engineering Mathematics.',
    icon: 'Cpu',
    totalMarks: 100,
    defaultDurationMinutes: 180,
  },
  {
    name: 'Electronics and Communication Engineering',
    code: 'EC',
    description: 'GATE EC syllabus covering Signals & Systems, Communications, Electromagnetics, and VLSI.',
    icon: 'Radio',
    totalMarks: 100,
    defaultDurationMinutes: 180,
  },
  {
    name: 'Electrical Engineering',
    code: 'EE',
    description: 'GATE EE syllabus covering Power Systems, Electrical Machines, Control Systems, and Power Electronics.',
    icon: 'Zap',
    totalMarks: 100,
    defaultDurationMinutes: 180,
  },
  {
    name: 'Mechanical Engineering',
    code: 'ME',
    description: 'GATE ME syllabus covering Thermodynamics, Fluid Mechanics, Manufacturing, and Solid Mechanics.',
    icon: 'Settings',
    totalMarks: 100,
    defaultDurationMinutes: 180,
  },
  {
    name: 'Civil Engineering',
    code: 'CE',
    description: 'GATE CE syllabus covering Structural Engineering, Geotechnical, Environmental, and Transportation.',
    icon: 'Building',
    totalMarks: 100,
    defaultDurationMinutes: 180,
  },
];

export const getSeedSubjectsAndTopics = (csBranchId) => {
  const subjects = [
    {
      name: 'General Aptitude',
      code: 'GA',
      branchId: csBranchId,
      category: 'General Aptitude',
      weightageDefault: 15,
      description: 'Verbal ability, quantitative aptitude, analytical reasoning, and spatial aptitude.',
      order: 1,
    },
    {
      name: 'Engineering Mathematics',
      code: 'EM',
      branchId: csBranchId,
      category: 'Engineering Mathematics',
      weightageDefault: 13,
      description: 'Discrete Mathematics, Linear Algebra, Calculus, and Probability.',
      order: 2,
    },
    {
      name: 'Digital Logic',
      code: 'DL',
      branchId: csBranchId,
      category: 'Core',
      weightageDefault: 5,
      description: 'Boolean algebra, combinational circuits, sequential circuits, and number representations.',
      order: 3,
    },
    {
      name: 'Computer Organization and Architecture',
      code: 'COA',
      branchId: csBranchId,
      category: 'Core',
      weightageDefault: 8,
      description: 'Machine instructions, memory hierarchy, cache mapping, pipelining, and I/O interface.',
      order: 4,
    },
    {
      name: 'Programming and Data Structures',
      code: 'PDS',
      branchId: csBranchId,
      category: 'Core',
      weightageDefault: 10,
      description: 'C programming, recursion, arrays, stacks, queues, linked lists, and binary search trees.',
      order: 5,
    },
    {
      name: 'Algorithms',
      code: 'ALGO',
      branchId: csBranchId,
      category: 'Core',
      weightageDefault: 9,
      description: 'Asymptotic analysis, divide-and-conquer, greedy, dynamic programming, and graph algorithms.',
      order: 6,
    },
    {
      name: 'Theory of Computation',
      code: 'TOC',
      branchId: csBranchId,
      category: 'Core',
      weightageDefault: 8,
      description: 'Regular expressions, finite automata, context-free grammars, pushdown automata, and Turing machines.',
      order: 7,
    },
    {
      name: 'Compiler Design',
      code: 'CD',
      branchId: csBranchId,
      category: 'Core',
      weightageDefault: 5,
      description: 'Lexical analysis, parsing, syntax-directed translation, intermediate code generation, and optimization.',
      order: 8,
    },
    {
      name: 'Operating Systems',
      code: 'OS',
      branchId: csBranchId,
      category: 'Core',
      weightageDefault: 9,
      description: 'Process management, CPU scheduling, synchronization, deadlocks, virtual memory, and file systems.',
      order: 9,
    },
    {
      name: 'Databases',
      code: 'DBMS',
      branchId: csBranchId,
      category: 'Core',
      weightageDefault: 9,
      description: 'ER models, relational algebra, SQL, normalization, transactions, indexing, and B+ trees.',
      order: 10,
    },
    {
      name: 'Computer Networks',
      code: 'CN',
      branchId: csBranchId,
      category: 'Core',
      weightageDefault: 9,
      description: 'OSI/TCP-IP layers, flow and error control, IPv4/IPv6 addressing, routing, TCP/UDP, and application protocols.',
      order: 11,
    },
  ];

  const topics = [
    // General Aptitude
    {
      name: 'Verbal Ability & Grammar',
      code: 'GA-VERB',
      subjectName: 'General Aptitude',
      description: 'English grammar, sentence completion, verbal analogies, and reading comprehension.',
      subtopics: ['Subject-verb agreement', 'Vocabulary', 'Critical reasoning'],
      keywords: ['passage', 'grammatically', 'analogy', 'sentence', 'antonym', 'synonym', 'spelling'],
      order: 1,
    },
    {
      name: 'Quantitative Aptitude',
      code: 'GA-QUANT',
      subjectName: 'General Aptitude',
      description: 'Percentages, ratios, time-speed-distance, permutations, combinations, and data interpretation.',
      subtopics: ['Ratios and Proportions', 'Time & Work', 'Probability basics'],
      keywords: ['ratio', 'percentage', 'speed', 'distance', 'work', 'profit', 'loss', 'average', 'interest'],
      order: 2,
    },
    {
      name: 'Analytical & Spatial Reasoning',
      code: 'GA-ANLYT',
      subjectName: 'General Aptitude',
      description: 'Deductive reasoning, pattern recognition, spatial folding, and logical puzzles.',
      subtopics: ['Pattern folding', 'Syllogisms', 'Blood relations'],
      keywords: ['conclude', 'pattern', 'fold', 'cube', 'mirror image', 'deduction', 'statement'],
      order: 3,
    },

    // Engineering Mathematics
    {
      name: 'Discrete Mathematics & Graph Theory',
      code: 'EM-DISC',
      subjectName: 'Engineering Mathematics',
      description: 'Propositional logic, predicate logic, sets, relations, partial orders, lattices, and graph coloring.',
      subtopics: ['Propositional Logic', 'Equivalence Relations', 'Eulerian & Hamiltonian Graphs'],
      keywords: ['proposition', 'predicate', 'equivalence relation', 'lattice', 'hamiltonian', 'eulerian', 'isomorphism', 'planar graph', 'chromatic'],
      order: 1,
    },
    {
      name: 'Linear Algebra',
      code: 'EM-LALG',
      subjectName: 'Engineering Mathematics',
      description: 'Matrices, determinants, system of linear equations, eigenvalues, and eigenvectors.',
      subtopics: ['Rank of Matrix', 'Eigenvalues & Eigenvectors', 'Cayley-Hamilton Theorem'],
      keywords: ['matrix', 'determinant', 'eigenvalue', 'eigenvector', 'rank', 'linear independence', 'characteristic equation', 'trace'],
      order: 2,
    },
    {
      name: 'Probability and Statistics',
      code: 'EM-PROB',
      subjectName: 'Engineering Mathematics',
      description: 'Conditional probability, Bayes theorem, random variables, Poisson, Binomial, and Normal distributions.',
      subtopics: ['Bayes Theorem', 'Expectation & Variance', 'Poisson Distribution'],
      keywords: ['probability', 'bayes', 'random variable', 'poisson', 'binomial', 'variance', 'expectation', 'standard deviation', 'dice'],
      order: 3,
    },
    {
      name: 'Calculus',
      code: 'EM-CALC',
      subjectName: 'Engineering Mathematics',
      description: 'Limits, continuity, differentiability, maxima and minima, mean value theorem, and definite integrals.',
      subtopics: ['Limits and Continuity', 'Maxima and Minima', 'Definite Integrals'],
      keywords: ['limit', 'integral', 'derivative', 'maxima', 'minima', 'continuous', 'differentiable'],
      order: 4,
    },

    // Theory of Computation
    {
      name: 'Finite Automata & Regular Languages',
      code: 'TOC-REG',
      subjectName: 'Theory of Computation',
      description: 'DFA, NFA, epsilon-NFA, regular expressions, minimization of DFA, and pumping lemma for regular languages.',
      subtopics: ['DFA Minimization', 'NFA to DFA Conversion', 'Pumping Lemma'],
      keywords: ['dfa', 'nfa', 'regular expression', 'finite automata', 'minimization', 'pumping lemma', 'regular language', 'myhill nerode', 'states'],
      order: 1,
    },
    {
      name: 'Context-Free Languages & Pushdown Automata',
      code: 'TOC-CFL',
      subjectName: 'Theory of Computation',
      description: 'Context-free grammars, ambiguity, Chomsky normal form, DPDA, and NPDA.',
      subtopics: ['Ambiguity in CFG', 'Pushdown Automata (DPDA vs NPDA)', 'CFL Closure Properties'],
      keywords: ['cfg', 'pda', 'pushdown', 'context free', 'dpda', 'npda', 'ambiguous grammar', 'chomsky', 'closure'],
      order: 2,
    },
    {
      name: 'Turing Machines & Decidability',
      code: 'TOC-TM',
      subjectName: 'Theory of Computation',
      description: 'Turing machines, recursively enumerable languages, Halting problem, Rice theorem, and undecidability.',
      subtopics: ['Halting Problem', 'Rice Theorem', 'Post Correspondence Problem (PCP)'],
      keywords: ['turing machine', 'decidable', 'undecidable', 'halting problem', 'recursively enumerable', 'rice theorem', 'pcp', 'turing'],
      order: 3,
    },

    // Programming and Data Structures
    {
      name: 'C Programming & Pointers',
      code: 'PDS-C',
      subjectName: 'Programming and Data Structures',
      description: 'Functions, parameter passing, recursion, pointers, arrays, and memory layout in C.',
      subtopics: ['Pointer Arithmetic', 'Recursion Analysis', 'Dynamic Memory'],
      keywords: ['pointer', 'recursion', 'function', 'printf', 'malloc', 'scope', 'parameter passing', 'output'],
      order: 1,
    },
    {
      name: 'Trees & Binary Search Trees',
      code: 'PDS-TREE',
      subjectName: 'Programming and Data Structures',
      description: 'Binary trees, tree traversals, BST insertions and deletions, AVL trees, and heaps.',
      subtopics: ['Inorder/Preorder/Postorder', 'AVL Rotations', 'Binary Heap'],
      keywords: ['binary search tree', 'bst', 'inorder', 'preorder', 'postorder', 'avl tree', 'binary tree', 'height balanced', 'heap'],
      order: 2,
    },
    {
      name: 'Linear Data Structures',
      code: 'PDS-LIN',
      subjectName: 'Programming and Data Structures',
      description: 'Arrays, Stacks, Queues, Linked Lists, and applications like infix-to-postfix.',
      subtopics: ['Stack Applications', 'Circular Queues', 'Linked List Reversal'],
      keywords: ['stack', 'queue', 'linked list', 'postfix', 'prefix', 'circular queue', 'doubly linked list'],
      order: 3,
    },

    // Algorithms
    {
      name: 'Asymptotic Analysis & Recurrences',
      code: 'ALGO-ASYMP',
      subjectName: 'Algorithms',
      description: 'Big-O, Big-Omega, Theta notations, Master Theorem, and substitution method.',
      subtopics: ['Master Theorem', 'Time Complexity Analysis', 'Space Complexity'],
      keywords: ['time complexity', 'master theorem', 'asymptotic', 'recurrence', 'big o', 'theta', 'omega'],
      order: 1,
    },
    {
      name: 'Dynamic Programming & Greedy',
      code: 'ALGO-DP',
      subjectName: 'Algorithms',
      description: 'Knapsack problem, longest common subsequence, Huffman coding, Dijkstra, and Kruskal/Prim algorithms.',
      subtopics: ['0/1 Knapsack', 'LCS', 'Dijkstra Shortest Path', 'Minimum Spanning Tree'],
      keywords: ['dynamic programming', 'greedy', 'knapsack', 'lcs', 'dijkstra', 'kruskal', 'prims', 'shortest path', 'bellman'],
      order: 2,
    },
    {
      name: 'Sorting & Searching',
      code: 'ALGO-SORT',
      subjectName: 'Algorithms',
      description: 'Quick sort, merge sort, heap sort, comparison lower bounds, and binary search.',
      subtopics: ['Quick Sort Partitioning', 'Heap Sort', 'Search Comparisons'],
      keywords: ['quicksort', 'mergesort', 'sorting', 'heapsort', 'binary search', 'comparison', 'partition'],
      order: 3,
    },

    // Databases
    {
      name: 'Relational Model, SQL & Relational Algebra',
      code: 'DBMS-SQL',
      subjectName: 'Databases',
      description: 'Tuples, relational algebra operations, joins, nested SQL queries, and integrity constraints.',
      subtopics: ['Relational Algebra', 'Nested SQL Queries', 'Group By & Having'],
      keywords: ['sql', 'relational algebra', 'select', 'join', 'outer join', 'foreign key', 'group by', 'schema', 'tuple'],
      order: 1,
    },
    {
      name: 'Normalization & Functional Dependencies',
      code: 'DBMS-NORM',
      subjectName: 'Databases',
      description: 'Canonical cover, candidate keys, 1NF, 2NF, 3NF, BCNF, lossless join, and dependency preservation.',
      subtopics: ['Candidate Keys Finding', 'BCNF vs 3NF', 'Lossless Join Decomposition'],
      keywords: ['functional dependency', 'candidate key', 'bcnf', '3nf', 'normalization', 'lossless', 'dependency preservation', 'normal form'],
      order: 2,
    },
    {
      name: 'Transactions, Concurrency & Indexing',
      code: 'DBMS-TXN',
      subjectName: 'Databases',
      description: 'ACID properties, serializability, 2PL, deadlock prevention, B-trees, and B+ trees.',
      subtopics: ['Conflict Serializability', 'Two-Phase Locking (2PL)', 'B+ Tree Indexing'],
      keywords: ['serializability', 'transaction', '2pl', 'conflict serializable', 'b+ tree', 'b tree', 'acid', 'schedule', 'lock'],
      order: 3,
    },

    // Operating Systems
    {
      name: 'CPU Scheduling & Process Synchronization',
      code: 'OS-SYNC',
      subjectName: 'Operating Systems',
      description: 'FCFS, SJF, Round Robin, Semaphores, Mutex, Classical IPC problems, and Petersons algorithm.',
      subtopics: ['Semaphores & Mutex', 'Round Robin Scheduling', 'Producer-Consumer Problem'],
      keywords: ['semaphore', 'cpu scheduling', 'round robin', 'turnaround time', 'critical section', 'process synchronization', 'mutex', 'burst'],
      order: 1,
    },
    {
      name: 'Deadlocks & Memory Management',
      code: 'OS-MEM',
      subjectName: 'Operating Systems',
      description: 'Resource allocation graph, Bankers algorithm, Paging, TLB, Page replacement algorithms, and Virtual Memory.',
      subtopics: ['Bankers Algorithm', 'TLB & Paging Address Translation', 'LRU / FIFO Page Replacement'],
      keywords: ['deadlock', 'banker', 'paging', 'virtual memory', 'tlb', 'page replacement', 'lru', 'page fault', 'fifo', 'page table'],
      order: 2,
    },
    {
      name: 'File Systems & Storage',
      code: 'OS-FILE',
      subjectName: 'Operating Systems',
      description: 'Inodes, directory structures, disk scheduling (SCAN, C-SCAN, SSTF, LOOK), and disk I/O.',
      subtopics: ['Disk Scheduling algorithms', 'Inode pointers', 'File allocation'],
      keywords: ['inode', 'disk scheduling', 'c-scan', 'sstf', 'seek time', 'cylinder', 'file system'],
      order: 3,
    },

    // Computer Networks
    {
      name: 'IP Addressing & Subnetting',
      code: 'CN-IP',
      subjectName: 'Computer Networks',
      description: 'Classless Inter-Domain Routing (CIDR), Subnet masks, Supernetting, and IP fragmentation.',
      subtopics: ['CIDR Subnetting', 'IP Header & Fragmentation', 'Broadcast Address'],
      keywords: ['ip address', 'subnet', 'cidr', 'subnet mask', 'fragmentation', 'mtu', 'routing table', 'host'],
      order: 1,
    },
    {
      name: 'Transport & Data Link Protocols',
      code: 'CN-PROTO',
      subjectName: 'Computer Networks',
      description: 'Sliding window protocols (Go-Back-N, Selective Repeat), TCP flow and congestion control, and TCP 3-way handshake.',
      subtopics: ['Sliding Window (GBN, SR)', 'TCP Congestion Control (Slow Start, AIMD)', 'UDP vs TCP'],
      keywords: ['tcp', 'sliding window', 'go back n', 'selective repeat', 'congestion window', 'slow start', 'aimd', 'flow control', 'handshake'],
      order: 2,
    },
    {
      name: 'Routing Algorithms & Application Layer',
      code: 'CN-ROUTE',
      subjectName: 'Computer Networks',
      description: 'Distance Vector, Link State routing, DNS, HTTP, SMTP, and Network Security (RSA, symmetric crypto).',
      subtopics: ['Distance Vector Routing', 'DNS queries', 'RSA Algorithm'],
      keywords: ['distance vector', 'link state', 'dijkstra routing', 'dns', 'http', 'rsa', 'cryptography'],
      order: 3,
    },

    // Digital Logic & COA
    {
      name: 'Combinational & Sequential Circuits',
      code: 'DL-CIRC',
      subjectName: 'Digital Logic',
      description: 'Multiplexers, Decoders, K-maps, Flip-Flops (JK, D, T), Counters, and State Machines.',
      subtopics: ['K-Map Simplification', 'Multiplexer Implementation', 'Mod-N Counters'],
      keywords: ['k-map', 'multiplexer', 'flip flop', 'boolean algebra', 'counter', 'decoder', 'mux', 'sop', 'pos'],
      order: 1,
    },
    {
      name: 'Number Representation & Logic Gates',
      code: 'DL-NUM',
      subjectName: 'Digital Logic',
      description: '2s complement arithmetic, floating point representation (IEEE 754), and logic minimization.',
      subtopics: ['2s complement representation', 'IEEE 754 single precision', 'Universal Gates'],
      keywords: ['2s complement', 'ieee 754', 'floating point', 'nand', 'nor', 'xor', 'overflow'],
      order: 2,
    },
    {
      name: 'Memory Hierarchy & Cache Mapping',
      code: 'COA-CACHE',
      subjectName: 'Computer Organization and Architecture',
      description: 'Direct mapping, Associative mapping, Set-associative cache, Hit latency, and Average Memory Access Time (AMAT).',
      subtopics: ['Set-Associative Cache', 'AMAT Calculation', 'Cache Tag/Set Bits'],
      keywords: ['cache', 'set associative', 'amat', 'hit ratio', 'direct mapped', 'tag bits', 'memory hierarchy', 'miss penalty'],
      order: 1,
    },
    {
      name: 'Pipelining & Hazards',
      code: 'COA-PIPE',
      subjectName: 'Computer Organization and Architecture',
      description: 'Instruction pipelining, speedup, branch penalty, data hazards, structural hazards, and forwarding.',
      subtopics: ['Pipeline Speedup', 'Data Hazards & Forwarding', 'Branch Penalty'],
      keywords: ['pipelining', 'hazard', 'speedup', 'clock cycle', 'branch penalty', 'forwarding', 'cpi', 'stage'],
      order: 2,
    },
    {
      name: 'Instruction Formats & Addressing Modes',
      code: 'COA-INST',
      subjectName: 'Computer Organization and Architecture',
      description: 'Addressing modes, register transfer language, microprogramming, and ALU design.',
      subtopics: ['Addressing Modes', 'Instruction Decoding', 'Interrupts'],
      keywords: ['addressing mode', 'instruction format', 'opcode', 'effective address', 'interrupt', 'dma'],
      order: 3,
    },

    // Compiler Design
    {
      name: 'Lexical Analysis & Parsing',
      code: 'CD-PARSE',
      subjectName: 'Compiler Design',
      description: 'Lexical analyzer, tokens, LL(1) parsing, LR(0), SLR(1), LALR(1), and CLR(1) parsers.',
      subtopics: ['LL(1) First and Follow', 'LR Parsing Tables', 'Shift-Reduce Conflicts'],
      keywords: ['ll(1)', 'lr(0)', 'slr(1)', 'lalr', 'clr', 'first', 'follow', 'parser', 'shift reduce', 'token'],
      order: 1,
    },
    {
      name: 'Syntax-Directed Translation & Intermediate Code',
      code: 'CD-SDT',
      subjectName: 'Compiler Design',
      description: 'S-attributed and L-attributed definitions, 3-address code, and syntax trees.',
      subtopics: ['S-attributed vs L-attributed', 'Three Address Code', 'Static Single Assignment'],
      keywords: ['sdt', 's-attributed', 'l-attributed', 'three address code', 'quadruple', 'triple', 'syntax tree'],
      order: 2,
    },
    {
      name: 'Code Optimization & Runtime Environments',
      code: 'CD-OPT',
      subjectName: 'Compiler Design',
      description: 'Basic blocks, flow graphs, loop optimization, dead code elimination, and activation records.',
      subtopics: ['Basic Block Identification', 'Loop Invariant Code Motion', 'Activation Records'],
      keywords: ['basic block', 'flow graph', 'dead code', 'loop invariant', 'optimization', 'activation record', 'stack allocation'],
      order: 3,
    },
  ];

  return { subjects, topics };
};

export const getSeedQuestions = () => [
  // -------------------------------------------------------------
  // GENERAL APTITUDE (GA) - 10 Unique Questions (15 Marks)
  // -------------------------------------------------------------
  {
    subjectName: 'General Aptitude',
    topicName: 'Verbal Ability & Grammar',
    year: 2026,
    paper: 'GATE CSE 2026',
    questionNumber: 1,
    questionText: 'Select the grammatically correct sentence from the options given below:',
    options: [
      { key: 'A', text: 'Neither the manager nor the employees was present at the conference.' },
      { key: 'B', text: 'Neither the manager nor the employees were present at the conference.' },
      { key: 'C', text: 'Neither the manager nor the employees has been present at the conference.' },
      { key: 'D', text: 'Neither the manager or the employees was present at the conference.' },
    ],
    correctAnswer: 'B',
    questionType: 'MCQ',
    marks: 1,
    negativeMarks: 0.33,
    difficulty: 'easy',
    explanation: 'In "neither...nor" with compound subjects, the verb agrees with the closer subject ("employees" -> plural "were").',
  },
  {
    subjectName: 'General Aptitude',
    topicName: 'Verbal Ability & Grammar',
    year: 2025,
    paper: 'GATE CSE 2025 Set 1',
    questionNumber: 2,
    questionText: 'Fill in the blank with the most appropriate word:\nThe committee decided to ________ the proposal until further empirical evidence was collected.',
    options: [
      { key: 'A', text: 'defer' },
      { key: 'B', text: 'differ' },
      { key: 'C', text: 'defy' },
      { key: 'D', text: 'defuse' },
    ],
    correctAnswer: 'A',
    questionType: 'MCQ',
    marks: 1,
    negativeMarks: 0.33,
    difficulty: 'easy',
    explanation: '"Defer" means to postpone or delay an action until a future time.',
  },
  {
    subjectName: 'General Aptitude',
    topicName: 'Quantitative Aptitude',
    year: 2026,
    paper: 'GATE CSE 2026',
    questionNumber: 3,
    questionText: 'If 12 men or 18 women can complete a construction project in 14 days, in how many days can 8 men and 16 women complete the same project?',
    natRange: { min: 9, max: 9, exact: 9 },
    correctAnswer: 9,
    questionType: 'NAT',
    marks: 1,
    negativeMarks: 0,
    difficulty: 'medium',
    explanation: '12 Men = 18 Women => 1 Man = 1.5 Women. 8 Men + 16 Women = 8(1.5) + 16 = 28 Women. Total work = 18 * 14 = 252 woman-days. Days required = 252 / 28 = 9 days.',
  },
  {
    subjectName: 'General Aptitude',
    topicName: 'Quantitative Aptitude',
    year: 2025,
    paper: 'GATE CSE 2025 Set 2',
    questionNumber: 4,
    questionText: 'The average weight of 8 persons increases by 2.5 kg when a new person replaces one of them who weighs 65 kg. What is the weight of the new person (in kg)?',
    natRange: { min: 85, max: 85, exact: 85 },
    correctAnswer: 85,
    questionType: 'NAT',
    marks: 1,
    negativeMarks: 0,
    difficulty: 'easy',
    explanation: 'Total weight increase = 8 * 2.5 = 20 kg. Weight of new person = 65 + 20 = 85 kg.',
  },
  {
    subjectName: 'General Aptitude',
    topicName: 'Analytical & Spatial Reasoning',
    year: 2024,
    paper: 'GATE CSE 2024 Set 1',
    questionNumber: 5,
    questionText: 'Statements:\n1. All algorithms are programs.\n2. Some programs are scripts.\nConclusions:\nI. Some algorithms are scripts.\nII. Some scripts are programs.',
    options: [
      { key: 'A', text: 'Only conclusion I follows' },
      { key: 'B', text: 'Only conclusion II follows' },
      { key: 'C', text: 'Both conclusions I and II follow' },
      { key: 'D', text: 'Neither conclusion I nor II follows' },
    ],
    correctAnswer: 'B',
    questionType: 'MCQ',
    marks: 1,
    negativeMarks: 0.33,
    difficulty: 'easy',
    explanation: 'Conversion of "Some programs are scripts" yields "Some scripts are programs" (Conclusion II).',
  },
  {
    subjectName: 'General Aptitude',
    topicName: 'Quantitative Aptitude',
    year: 2025,
    paper: 'GATE CSE 2025 Set 1',
    questionNumber: 6,
    questionText: 'A train 240 meters long passes a pole in 24 seconds. How long (in seconds) will it take to pass a platform 650 meters long at the same speed?',
    natRange: { min: 89, max: 89, exact: 89 },
    correctAnswer: 89,
    questionType: 'NAT',
    marks: 2,
    negativeMarks: 0,
    difficulty: 'medium',
    explanation: 'Speed = 240 / 24 = 10 m/s. Total distance = 240 + 650 = 890 m. Time = 890 / 10 = 89 seconds.',
  },
  {
    subjectName: 'General Aptitude',
    topicName: 'Quantitative Aptitude',
    year: 2025,
    paper: 'GATE CSE 2025 Set 2',
    questionNumber: 7,
    questionText: 'The ratio of boys to girls in a class is 5 : 3. If 16% of the boys and 20% of the girls are scholarship holders, what percentage of the total class does NOT receive a scholarship?',
    options: [
      { key: 'A', text: '82.5%' },
      { key: 'B', text: '80.0%' },
      { key: 'C', text: '85.0%' },
      { key: 'D', text: '78.5%' },
    ],
    correctAnswer: 'A',
    questionType: 'MCQ',
    marks: 2,
    negativeMarks: 0.66,
    difficulty: 'medium',
    explanation: 'Let boys = 500, girls = 300 (total = 800). Scholarship holders = 80 + 60 = 140. Non-scholarship = 660 / 800 = 82.5%.',
  },
  {
    subjectName: 'General Aptitude',
    topicName: 'Verbal Ability & Grammar',
    year: 2024,
    paper: 'GATE CSE 2024 Set 2',
    questionNumber: 8,
    questionText: 'Given below are four sentences in jumbled order. Pick the option that gives their logical connection:\nP: The invention of the transistor revolutionized computing.\nQ: Before transistors, computers relied on bulky vacuum tubes.\nR: Consequently, modern processors contain billions of components.\nS: Vacuum tubes consumed excessive power and generated significant heat.',
    options: [
      { key: 'A', text: 'Q - S - P - R' },
      { key: 'B', text: 'P - Q - R - S' },
      { key: 'C', text: 'Q - P - S - R' },
      { key: 'D', text: 'P - R - Q - S' },
    ],
    correctAnswer: 'A',
    questionType: 'MCQ',
    marks: 2,
    negativeMarks: 0.66,
    difficulty: 'medium',
    explanation: 'The logical narrative starts with vacuum tubes (Q), explains their limitation (S), introduces the transistor solution (P), and concludes with the outcome (R).',
  },
  {
    subjectName: 'General Aptitude',
    topicName: 'Analytical & Spatial Reasoning',
    year: 2026,
    paper: 'GATE CSE 2026',
    questionNumber: 9,
    questionText: 'In a code language, \'ROUTER\' is encoded as \'TRWVGT\'. How is \'SWITCH\' encoded in the same rule?',
    options: [
      { key: 'A', text: 'UYKVEM' },
      { key: 'B', text: 'UYKVEJ' },
      { key: 'C', text: 'TXKVEM' },
      { key: 'D', text: 'UZKWEN' },
    ],
    correctAnswer: 'B',
    questionType: 'MCQ',
    marks: 2,
    negativeMarks: 0.66,
    difficulty: 'medium',
    explanation: 'Each character is shifted by +2 positions in alphabetical order: S(+2)=U, W(+2)=Y, I(+2)=K, T(+2)=V, C(+2)=E, H(+2)=J -> UYKVEJ.',
  },
  {
    subjectName: 'General Aptitude',
    topicName: 'Quantitative Aptitude',
    year: 2023,
    paper: 'GATE CSE 2023',
    questionNumber: 10,
    questionText: 'A circle of radius r is inscribed inside a square of side length 2r. What is the ratio of the area of the square to the area of the circle?',
    options: [
      { key: 'A', text: '4 / π' },
      { key: 'B', text: 'π / 4' },
      { key: 'C', text: '2 / π' },
      { key: 'D', text: '4π' },
    ],
    correctAnswer: 'A',
    questionType: 'MCQ',
    marks: 2,
    negativeMarks: 0.66,
    difficulty: 'easy',
    explanation: 'Area of square = (2r)^2 = 4r^2. Area of circle = π r^2. Ratio = 4r^2 / (π r^2) = 4 / π.',
  },

  // -------------------------------------------------------------
  // ENGINEERING MATHEMATICS (EM) - 9 Unique Questions (13 Marks)
  // -------------------------------------------------------------
  {
    subjectName: 'Engineering Mathematics',
    topicName: 'Linear Algebra',
    year: 2026,
    paper: 'GATE CSE 2026',
    questionNumber: 11,
    questionText: 'For a 2 x 2 matrix M, the trace of M is 7 and the determinant of M is 12. What are the eigenvalues of matrix M?',
    options: [
      { key: 'A', text: '3 and 4' },
      { key: 'B', text: '2 and 6' },
      { key: 'C', text: '1 and 12' },
      { key: 'D', text: '5 and 2' },
    ],
    correctAnswer: 'A',
    questionType: 'MCQ',
    marks: 1,
    negativeMarks: 0.33,
    difficulty: 'easy',
    explanation: 'Roots of characteristic equation λ^2 - 7λ + 12 = 0 are (λ - 3)(λ - 4) = 0 => 3 and 4.',
  },
  {
    subjectName: 'Engineering Mathematics',
    topicName: 'Probability and Statistics',
    year: 2025,
    paper: 'GATE CSE 2025 Set 2',
    questionNumber: 12,
    questionText: 'Two unbiased dice are rolled simultaneously. What is the probability that the sum of the numbers appearing on the top faces is at least 10?',
    options: [
      { key: 'A', text: '1/6' },
      { key: 'B', text: '1/12' },
      { key: 'C', text: '5/36' },
      { key: 'D', text: '7/36' },
    ],
    correctAnswer: 'A',
    questionType: 'MCQ',
    marks: 1,
    negativeMarks: 0.33,
    difficulty: 'easy',
    explanation: 'Sums >= 10: (4,6), (5,5), (6,4), (5,6), (6,5), (6,6) = 6 favorable outcomes. P = 6/36 = 1/6.',
  },
  {
    subjectName: 'Engineering Mathematics',
    topicName: 'Discrete Mathematics & Graph Theory',
    year: 2024,
    paper: 'GATE CSE 2024 Set 1',
    questionNumber: 13,
    questionText: 'What is the chromatic number of the complete bipartite graph K_{3, 4}?',
    natRange: { min: 2, max: 2, exact: 2 },
    correctAnswer: 2,
    questionType: 'NAT',
    marks: 1,
    negativeMarks: 0,
    difficulty: 'easy',
    explanation: 'Every connected bipartite graph with at least one edge has a chromatic number of 2.',
  },
  {
    subjectName: 'Engineering Mathematics',
    topicName: 'Calculus',
    year: 2026,
    paper: 'GATE CSE 2026',
    questionNumber: 14,
    questionText: 'What is the value of the limit lim_{x -> 0} (sin(5x) / tan(2x))?',
    options: [
      { key: 'A', text: '5/2' },
      { key: 'B', text: '2/5' },
      { key: 'C', text: '1' },
      { key: 'D', text: '0' },
    ],
    correctAnswer: 'A',
    questionType: 'MCQ',
    marks: 1,
    negativeMarks: 0.33,
    difficulty: 'easy',
    explanation: 'lim_{x->0} (sin(5x)/(5x) * 5) / (tan(2x)/(2x) * 2) = (1*5)/(1*2) = 5/2.',
  },
  {
    subjectName: 'Engineering Mathematics',
    topicName: 'Discrete Mathematics & Graph Theory',
    year: 2025,
    paper: 'GATE CSE 2025 Set 1',
    questionNumber: 15,
    questionText: 'Let G be a simple connected graph with 8 vertices such that every vertex has degree at least 3. What is the minimum possible number of edges in G?',
    natRange: { min: 12, max: 12, exact: 12 },
    correctAnswer: 12,
    questionType: 'NAT',
    marks: 1,
    negativeMarks: 0,
    difficulty: 'medium',
    explanation: 'By Handshaking Lemma, Sum of degrees = 2E >= 8 * 3 = 24 => E >= 12.',
  },
  {
    subjectName: 'Engineering Mathematics',
    topicName: 'Discrete Mathematics & Graph Theory',
    year: 2025,
    paper: 'GATE CSE 2025 Set 1',
    questionNumber: 16,
    questionText: 'How many edges does a simple planar graph with 10 vertices and 7 faces have?',
    natRange: { min: 15, max: 15, exact: 15 },
    correctAnswer: 15,
    questionType: 'NAT',
    marks: 2,
    negativeMarks: 0,
    difficulty: 'medium',
    explanation: 'By Euler\'s formula for planar graphs: V - E + F = 2 => 10 - E + 7 = 2 => 17 - E = 2 => E = 15.',
  },
  {
    subjectName: 'Engineering Mathematics',
    topicName: 'Linear Algebra',
    year: 2024,
    paper: 'GATE CSE 2024 Set 2',
    questionNumber: 17,
    questionText: 'Let A be a 3 x 3 real symmetric matrix with eigenvalues 1, 2, and 3. What is the value of trace(A^2 + 2*A)?',
    natRange: { min: 26, max: 26, exact: 26 },
    correctAnswer: 26,
    questionType: 'NAT',
    marks: 2,
    negativeMarks: 0,
    difficulty: 'medium',
    explanation: 'Eigenvalues of A^2 + 2A are 1^2+2(1)=3, 2^2+2(2)=8, 3^2+2(3)=15. Trace = sum of eigenvalues = 3 + 8 + 15 = 26.',
  },
  {
    subjectName: 'Engineering Mathematics',
    topicName: 'Probability and Statistics',
    year: 2025,
    paper: 'GATE CSE 2025 Set 2',
    questionNumber: 18,
    questionText: 'A random variable X follows a Poisson distribution with mean λ = 2. What is the value of P(X >= 1)?',
    options: [
      { key: 'A', text: '1 - e^(-2)' },
      { key: 'B', text: 'e^(-2)' },
      { key: 'C', text: '1 - 2*e^(-2)' },
      { key: 'D', text: '2*e^(-2)' },
    ],
    correctAnswer: 'A',
    questionType: 'MCQ',
    marks: 2,
    negativeMarks: 0.66,
    difficulty: 'medium',
    explanation: 'P(X >= 1) = 1 - P(X = 0) = 1 - (e^(-2) * 2^0 / 0!) = 1 - e^(-2).',
  },
  {
    subjectName: 'Engineering Mathematics',
    topicName: 'Calculus',
    year: 2023,
    paper: 'GATE CSE 2023',
    questionNumber: 19,
    questionText: 'The value of the definite integral ∫ from 0 to 1 of x * e^x dx is:',
    options: [
      { key: 'A', text: '1' },
      { key: 'B', text: 'e - 1' },
      { key: 'C', text: 'e - 2' },
      { key: 'D', text: '2e - 1' },
    ],
    correctAnswer: 'A',
    questionType: 'MCQ',
    marks: 2,
    negativeMarks: 0.66,
    difficulty: 'medium',
    explanation: 'Integration by parts: [x e^x - e^x] from 0 to 1 = (1*e - e) - (0 - 1) = 0 - (-1) = 1.',
  },

  // -------------------------------------------------------------
  // THEORY OF COMPUTATION (TOC) - 7 Unique Questions (11 Marks)
  // -------------------------------------------------------------
  {
    subjectName: 'Theory of Computation',
    topicName: 'Finite Automata & Regular Languages',
    year: 2026,
    paper: 'GATE CSE 2026',
    questionNumber: 20,
    questionText: 'What is the minimum number of states required in a Deterministic Finite Automaton (DFA) that accepts all binary strings containing an even number of 0s and an odd number of 1s?',
    options: [
      { key: 'A', text: '2 states' },
      { key: 'B', text: '3 states' },
      { key: 'C', text: '4 states' },
      { key: 'D', text: '5 states' },
    ],
    correctAnswer: 'C',
    questionType: 'MCQ',
    marks: 1,
    negativeMarks: 0.33,
    difficulty: 'easy',
    explanation: 'The states track (even/odd 0s, even/odd 1s) = 2 x 2 = 4 distinct states.',
  },
  {
    subjectName: 'Theory of Computation',
    topicName: 'Finite Automata & Regular Languages',
    year: 2024,
    paper: 'GATE CSE 2024 Set 1',
    questionNumber: 21,
    questionText: 'Let L be the language over {a, b} consisting of all strings starting with \'ab\'. What is the minimum number of states in a minimal DFA accepting L?',
    natRange: { min: 4, max: 4, exact: 4 },
    correctAnswer: 4,
    questionType: 'NAT',
    marks: 1,
    negativeMarks: 0,
    difficulty: 'easy',
    explanation: 'States: q0 (start), q1 (after \'a\'), q2 (after \'ab\' - accepting trap), q3 (dead state for illegal prefix). Total = 4 states.',
  },
  {
    subjectName: 'Theory of Computation',
    topicName: 'Context-Free Languages & Pushdown Automata',
    year: 2025,
    paper: 'GATE CSE 2025 Set 1',
    questionNumber: 22,
    questionText: 'Which of the following formal grammars is inherently AMBIGUOUS?',
    options: [
      { key: 'A', text: 'S -> a S b | ε' },
      { key: 'B', text: 'S -> S S | a | b' },
      { key: 'C', text: 'S -> a S | b S | ε' },
      { key: 'D', text: 'S -> ( S ) | ε' },
    ],
    correctAnswer: 'B',
    questionType: 'MCQ',
    marks: 1,
    negativeMarks: 0.33,
    difficulty: 'medium',
    explanation: 'S -> SS allows multiple distinct leftmost derivations / parse trees for strings like "aaa".',
  },
  {
    subjectName: 'Theory of Computation',
    topicName: 'Finite Automata & Regular Languages',
    year: 2025,
    paper: 'GATE CSE 2025 Set 1',
    questionNumber: 23,
    questionText: 'Consider the regular expression R = (a + b)* a (a + b) over the alphabet Σ = {a, b}. What is the minimum number of states in the minimal DFA accepting the language denoted by R?',
    options: [
      { key: 'A', text: '3' },
      { key: 'B', text: '4' },
      { key: 'C', text: '5' },
      { key: 'D', text: '6' },
    ],
    correctAnswer: 'B',
    questionType: 'MCQ',
    marks: 2,
    negativeMarks: 0.66,
    difficulty: 'medium',
    explanation: 'Language represents strings with \'a\' at the second position from the right end: 2^2 = 4 states.',
  },
  {
    subjectName: 'Theory of Computation',
    topicName: 'Context-Free Languages & Pushdown Automata',
    year: 2024,
    paper: 'GATE CSE 2024 Set 2',
    questionNumber: 24,
    questionText: 'Which of the following languages is/are Context-Free Language(s)?\nL1 = { a^n b^n c^m | n >= 0, m >= 0 }\nL2 = { a^n b^m c^n | n >= 0, m >= 0 }\nL3 = { a^n b^n c^n | n >= 0 }',
    options: [
      { key: 'A', text: 'L1 only' },
      { key: 'B', text: 'L1 and L2 only' },
      { key: 'C', text: 'L1, L2 and L3' },
      { key: 'D', text: 'L3 only' },
    ],
    correctAnswer: 'B',
    questionType: 'MCQ',
    marks: 2,
    negativeMarks: 0.66,
    difficulty: 'medium',
    explanation: 'L1 and L2 only require 1 simultaneous count comparison (pushdown stack sufficient). L3 requires 2 comparisons (not CFL).',
  },
  {
    subjectName: 'Theory of Computation',
    topicName: 'Turing Machines & Decidability',
    year: 2025,
    paper: 'GATE CSE 2025 Set 2',
    questionNumber: 25,
    questionText: 'Which of the following problems is/are UNDECIDABLE for Turing Machines?\nS1: Whether a given Turing Machine halts on an empty tape.\nS2: Whether the language accepted by a given Turing machine is regular.\nS3: Whether a given DFA accepts the empty language.',
    options: [
      { key: 'A', text: 'S1 and S2 only' },
      { key: 'B', text: 'S1 only' },
      { key: 'C', text: 'S2 and S3 only' },
      { key: 'D', text: 'S1, S2 and S3' },
    ],
    correctAnswer: 'A',
    questionType: 'MCQ',
    marks: 2,
    negativeMarks: 0.66,
    difficulty: 'hard',
    explanation: 'S1 (Halting problem) is undecidable. S2 (Regularity of TM language) is undecidable by Rice Theorem. S3 (DFA emptiness) is decidable.',
  },
  {
    subjectName: 'Theory of Computation',
    topicName: 'Context-Free Languages & Pushdown Automata',
    year: 2023,
    paper: 'GATE CSE 2023',
    questionNumber: 26,
    questionText: 'Which of the following statements is/are TRUE regarding closure properties of language classes?',
    options: [
      { key: 'A', text: 'Regular languages are closed under intersection and complementation.' },
      { key: 'B', text: 'Context-Free languages are closed under intersection.' },
      { key: 'C', text: 'Deterministic Context-Free languages (DCFL) are closed under complementation.' },
      { key: 'D', text: 'Recursive languages are closed under intersection and complementation.' },
    ],
    correctAnswer: ['A', 'C', 'D'],
    questionType: 'MSQ',
    marks: 2,
    negativeMarks: 0,
    difficulty: 'hard',
    explanation: 'CFLs are NOT closed under intersection (B is false). Regular, DCFL (complement), and Recursive languages satisfy the respective statements.',
  },

  // -------------------------------------------------------------
  // PROGRAMMING & DATA STRUCTURES (PDS) - 7 Unique Questions (11 Marks)
  // -------------------------------------------------------------
  {
    subjectName: 'Programming and Data Structures',
    topicName: 'C Programming & Pointers',
    year: 2026,
    paper: 'GATE CSE 2026',
    questionNumber: 27,
    questionText: 'What is the output of the following C code snippet?\n\nint x = 5;\nint foo(int *p) {\n  *p = *p + 10;\n  return *p * 2;\n}\nint main() {\n  int y = foo(&x) + x;\n  printf("%d", y);\n  return 0;\n}',
    options: [
      { key: 'A', text: '45' },
      { key: 'B', text: '35' },
      { key: 'C', text: '30' },
      { key: 'D', text: '25' },
    ],
    correctAnswer: 'A',
    questionType: 'MCQ',
    marks: 1,
    negativeMarks: 0.33,
    difficulty: 'medium',
    explanation: 'In `foo(&x)`, *p becomes 15 and returns 30. Then y = 30 + 15 = 45.',
  },
  {
    subjectName: 'Programming and Data Structures',
    topicName: 'Trees & Binary Search Trees',
    year: 2025,
    paper: 'GATE CSE 2025 Set 2',
    questionNumber: 28,
    questionText: 'A binary search tree is constructed by inserting keys: 40, 20, 10, 30, 60, 50, 70 into an initially empty BST. What is the height of the resulting tree (counting edges)?',
    natRange: { min: 2, max: 2, exact: 2 },
    correctAnswer: 2,
    questionType: 'NAT',
    marks: 1,
    negativeMarks: 0,
    difficulty: 'easy',
    explanation: 'Root is 40. Depth 1 has 20 and 60. Depth 2 has 10, 30, 50, 70. Longest path is 2 edges (height = 2).',
  },
  {
    subjectName: 'Programming and Data Structures',
    topicName: 'Linear Data Structures',
    year: 2024,
    paper: 'GATE CSE 2024 Set 1',
    questionNumber: 29,
    questionText: 'An array A of size N is used to implement a circular queue with FRONT and REAR indices. What is the condition for the queue being FULL?',
    options: [
      { key: 'A', text: '(REAR + 1) % N == FRONT' },
      { key: 'B', text: 'REAR == FRONT' },
      { key: 'C', text: '(FRONT + 1) % N == REAR' },
      { key: 'D', text: 'REAR == N - 1' },
    ],
    correctAnswer: 'A',
    questionType: 'MCQ',
    marks: 1,
    negativeMarks: 0.33,
    difficulty: 'easy',
    explanation: 'In standard circular array queue of capacity N with 1 slot preserved, full condition is (REAR + 1) % N == FRONT.',
  },
  {
    subjectName: 'Programming and Data Structures',
    topicName: 'C Programming & Pointers',
    year: 2025,
    paper: 'GATE CSE 2025 Set 1',
    questionNumber: 30,
    questionText: 'What is the output of the recursive C function `fun(4, 3)`?\n\nint fun(int a, int b) {\n  if (b == 0) return 1;\n  if (b % 2 == 0) return fun(a * a, b / 2);\n  return a * fun(a * a, b / 2);\n}',
    natRange: { min: 64, max: 64, exact: 64 },
    correctAnswer: 64,
    questionType: 'NAT',
    marks: 2,
    negativeMarks: 0,
    difficulty: 'medium',
    explanation: 'This implements modular/fast exponentiation: 4^3 = 64.',
  },
  {
    subjectName: 'Programming and Data Structures',
    topicName: 'Trees & Binary Search Trees',
    year: 2024,
    paper: 'GATE CSE 2024 Set 2',
    questionNumber: 31,
    questionText: 'The preorder traversal of a binary search tree is 30, 20, 10, 15, 25, 40, 50. What is the postorder traversal of the tree?',
    options: [
      { key: 'A', text: '15, 10, 25, 20, 50, 40, 30' },
      { key: 'B', text: '10, 15, 20, 25, 30, 40, 50' },
      { key: 'C', text: '15, 25, 10, 20, 50, 40, 30' },
      { key: 'D', text: '15, 10, 20, 25, 40, 50, 30' },
    ],
    correctAnswer: 'A',
    questionType: 'MCQ',
    marks: 2,
    negativeMarks: 0.66,
    difficulty: 'medium',
    explanation: 'Reconstructing the BST from preorder and reading postorder gives: 15, 10, 25, 20, 50, 40, 30.',
  },
  {
    subjectName: 'Programming and Data Structures',
    topicName: 'Linear Data Structures',
    year: 2026,
    paper: 'GATE CSE 2026',
    questionNumber: 32,
    questionText: 'Which of the following data structures can be used to convert an infix mathematical expression to postfix notation in a single linear pass?',
    options: [
      { key: 'A', text: 'Stack' },
      { key: 'B', text: 'Queue' },
      { key: 'C', text: 'Min-Heap' },
      { key: 'D', text: 'Binary Search Tree' },
    ],
    correctAnswer: 'A',
    questionType: 'MCQ',
    marks: 2,
    negativeMarks: 0.66,
    difficulty: 'easy',
    explanation: 'A Stack is used to buffer operators according to precedence during infix to postfix conversion (Shunting-yard algorithm).',
  },
  {
    subjectName: 'Programming and Data Structures',
    topicName: 'Trees & Binary Search Trees',
    year: 2023,
    paper: 'GATE CSE 2023',
    questionNumber: 33,
    questionText: 'What is the minimum number of nodes in an AVL tree of height 4 (where tree with single root has height 0)?',
    natRange: { min: 12, max: 12, exact: 12 },
    correctAnswer: 12,
    questionType: 'NAT',
    marks: 2,
    negativeMarks: 0,
    difficulty: 'hard',
    explanation: 'N(0)=1, N(1)=2, N(2)=4, N(3)=7, N(4)=12 (Fibonacci recurrence N(h) = N(h-1) + N(h-2) + 1).',
  },

  // -------------------------------------------------------------
  // ALGORITHMS (ALGO) - 7 Unique Questions (11 Marks)
  // -------------------------------------------------------------
  {
    subjectName: 'Algorithms',
    topicName: 'Asymptotic Analysis & Recurrences',
    year: 2026,
    paper: 'GATE CSE 2026',
    questionNumber: 34,
    questionText: 'What is the tightest asymptotic time complexity of the recurrence T(n) = 4 T(n/2) + n^2 ?',
    options: [
      { key: 'A', text: 'Θ(n^2 log n)' },
      { key: 'B', text: 'Θ(n^2)' },
      { key: 'C', text: 'Θ(n^3)' },
      { key: 'D', text: 'Θ(n log n)' },
    ],
    correctAnswer: 'A',
    questionType: 'MCQ',
    marks: 1,
    negativeMarks: 0.33,
    difficulty: 'easy',
    explanation: 'Here a=4, b=2 => n^(log_2 4) = n^2. Since f(n) = n^2, by Master Theorem Case 2: T(n) = Θ(n^2 log n).',
  },
  {
    subjectName: 'Algorithms',
    topicName: 'Sorting & Searching',
    year: 2025,
    paper: 'GATE CSE 2025 Set 2',
    questionNumber: 35,
    questionText: 'What is the worst-case number of key comparisons required to find both the minimum and maximum elements in an unsorted array of n elements?',
    options: [
      { key: 'A', text: 'ceil(3n/2) - 2' },
      { key: 'B', text: '2n - 2' },
      { key: 'C', text: 'n - 1' },
      { key: 'D', text: 'n log n' },
    ],
    correctAnswer: 'A',
    questionType: 'MCQ',
    marks: 1,
    negativeMarks: 0.33,
    difficulty: 'easy',
    explanation: 'Pairwise tournament comparison finds min and max in ceil(3n/2) - 2 comparisons.',
  },
  {
    subjectName: 'Algorithms',
    topicName: 'Sorting & Searching',
    year: 2024,
    paper: 'GATE CSE 2024 Set 1',
    questionNumber: 36,
    questionText: 'What is the time complexity of building a max-heap of n elements using the bottom-up `Build-Heap` procedure?',
    options: [
      { key: 'A', text: 'O(n)' },
      { key: 'B', text: 'O(n log n)' },
      { key: 'C', text: 'O(n^2)' },
      { key: 'D', text: 'O(log n)' },
    ],
    correctAnswer: 'A',
    questionType: 'MCQ',
    marks: 1,
    negativeMarks: 0.33,
    difficulty: 'easy',
    explanation: 'Linear time O(n) is achieved because majority of nodes are near the leaves and take fewer downward swaps.',
  },
  {
    subjectName: 'Algorithms',
    topicName: 'Asymptotic Analysis & Recurrences',
    year: 2026,
    paper: 'GATE CSE 2026',
    questionNumber: 37,
    questionText: 'Consider the recurrence relation:\nT(n) = 2 * T(n / 2) + n * log(n), with T(1) = 1.\nWhat is the asymptotic time complexity of T(n)?',
    options: [
      { key: 'A', text: 'Θ(n log n)' },
      { key: 'B', text: 'Θ(n (log n)^2)' },
      { key: 'C', text: 'Θ(n^2)' },
      { key: 'D', text: 'Θ(n log(log n))' },
    ],
    correctAnswer: 'B',
    questionType: 'MCQ',
    marks: 2,
    negativeMarks: 0.66,
    difficulty: 'medium',
    explanation: 'By Master Theorem extended case where f(n) = n * (log n)^1 and n^(log_b a) = n^1: T(n) = Θ(n * (log n)^2).',
  },
  {
    subjectName: 'Algorithms',
    topicName: 'Dynamic Programming & Greedy',
    year: 2025,
    paper: 'GATE CSE 2025 Set 1',
    questionNumber: 38,
    questionText: 'Which of the following statements about graph algorithms is/are TRUE?',
    options: [
      { key: 'A', text: 'Dijkstra\'s algorithm may fail to compute shortest paths if the graph contains negative edge weights.' },
      { key: 'B', text: 'Bellman-Ford algorithm can detect negative weight cycles in a directed graph.' },
      { key: 'C', text: 'Prim\'s algorithm always produces a Minimum Spanning Tree even if negative edge weights exist (as long as no negative cycle exists).' },
      { key: 'D', text: 'Floyd-Warshall algorithm runs in O(V^2 log V) using a Fibonacci heap.' },
    ],
    correctAnswer: ['A', 'B', 'C'],
    questionType: 'MSQ',
    marks: 2,
    negativeMarks: 0,
    difficulty: 'hard',
    explanation: 'A, B, and C are correct. D is false because Floyd-Warshall runs in O(V^3) time.',
  },
  {
    subjectName: 'Algorithms',
    topicName: 'Dynamic Programming & Greedy',
    year: 2024,
    paper: 'GATE CSE 2024 Set 2',
    questionNumber: 39,
    questionText: 'What is the length of the Longest Common Subsequence (LCS) of sequences S1 = "ABCBDAB" and S2 = "BDCABA"?',
    natRange: { min: 4, max: 4, exact: 4 },
    correctAnswer: 4,
    questionType: 'NAT',
    marks: 2,
    negativeMarks: 0,
    difficulty: 'medium',
    explanation: 'LCS is "BCBA" or "BDAB" or "BCAB", which has length 4.',
  },
  {
    subjectName: 'Algorithms',
    topicName: 'Sorting & Searching',
    year: 2023,
    paper: 'GATE CSE 2023',
    questionNumber: 40,
    questionText: 'An array of 1000 distinct elements is sorted using QuickSort. In the worst case, how many comparisons will be performed?',
    natRange: { min: 499500, max: 499500, exact: 499500 },
    correctAnswer: 499500,
    questionType: 'NAT',
    marks: 2,
    negativeMarks: 0,
    difficulty: 'medium',
    explanation: 'Worst case comparisons = n(n-1)/2 = 1000 * 999 / 2 = 499,500.',
  },

  // -------------------------------------------------------------
  // DATABASES (DBMS) - 7 Unique Questions (11 Marks)
  // -------------------------------------------------------------
  {
    subjectName: 'Databases',
    topicName: 'Transactions, Concurrency & Indexing',
    year: 2025,
    paper: 'GATE CSE 2025 Set 1',
    questionNumber: 41,
    questionText: 'Consider a B+ tree of order 4 (i.e., maximum 4 pointers/child nodes per internal node). What is the minimum number of keys in a non-root internal node?',
    options: [
      { key: 'A', text: '1' },
      { key: 'B', text: '2' },
      { key: 'C', text: '3' },
      { key: 'D', text: '4' },
    ],
    correctAnswer: 'A',
    questionType: 'MCQ',
    marks: 1,
    negativeMarks: 0.33,
    difficulty: 'easy',
    explanation: 'Minimum pointers in non-root node of order 4 = ceil(4/2) = 2 pointers. Minimum keys = 2 - 1 = 1 key.',
  },
  {
    subjectName: 'Databases',
    topicName: 'Relational Model, SQL & Relational Algebra',
    year: 2024,
    paper: 'GATE CSE 2024 Set 1',
    questionNumber: 42,
    questionText: 'Which relational algebra operator is equivalent to the Cartesian product followed by a selection condition?',
    options: [
      { key: 'A', text: 'Theta Join' },
      { key: 'B', text: 'Projection' },
      { key: 'C', text: 'Union' },
      { key: 'D', text: 'Set Difference' },
    ],
    correctAnswer: 'A',
    questionType: 'MCQ',
    marks: 1,
    negativeMarks: 0.33,
    difficulty: 'easy',
    explanation: 'By definition, R ⨝_θ S = σ_θ (R × S).',
  },
  {
    subjectName: 'Databases',
    topicName: 'Normalization & Functional Dependencies',
    year: 2026,
    paper: 'GATE CSE 2026',
    questionNumber: 43,
    questionText: 'If every determinant in a relational schema R is a candidate key, then schema R is guaranteed to be in:',
    options: [
      { key: 'A', text: 'Boyce-Codd Normal Form (BCNF)' },
      { key: 'B', text: '3NF but not BCNF' },
      { key: 'C', text: '2NF only' },
      { key: 'D', text: '1NF only' },
    ],
    correctAnswer: 'A',
    questionType: 'MCQ',
    marks: 1,
    negativeMarks: 0.33,
    difficulty: 'easy',
    explanation: 'BCNF condition states that for every functional dependency X -> Y, X must be a superkey/candidate key.',
  },
  {
    subjectName: 'Databases',
    topicName: 'Relational Model, SQL & Relational Algebra',
    year: 2026,
    paper: 'GATE CSE 2026',
    questionNumber: 44,
    questionText: 'Consider a relation R(A, B, C, D) with functional dependencies:\nF = { A -> B, B -> C, C -> D, D -> A }.\nHow many candidate keys does the relation R possess?',
    natRange: { min: 4, max: 4, exact: 4 },
    correctAnswer: 4,
    questionType: 'NAT',
    marks: 2,
    negativeMarks: 0,
    difficulty: 'medium',
    explanation: 'The closures A+, B+, C+, and D+ each contain all 4 attributes. Thus, {A}, {B}, {C}, and {D} are all minimal candidate keys (Total = 4).',
  },
  {
    subjectName: 'Databases',
    topicName: 'Normalization & Functional Dependencies',
    year: 2024,
    paper: 'GATE CSE 2024 Set 2',
    questionNumber: 45,
    questionText: 'A relation R(P, Q, R, S, T) has functional dependencies:\nFD = { P -> Q, Q -> R, S -> T }.\nIn which normal form is relation R currently in?',
    options: [
      { key: 'A', text: '1NF but not 2NF' },
      { key: 'B', text: '2NF but not 3NF' },
      { key: 'C', text: '3NF but not BCNF' },
      { key: 'D', text: 'BCNF' },
    ],
    correctAnswer: 'A',
    questionType: 'MCQ',
    marks: 2,
    negativeMarks: 0.66,
    difficulty: 'medium',
    explanation: 'Candidate key is {P, S}. The FD P -> Q is a partial dependency of non-prime attribute Q on prime attribute P, which violates 2NF.',
  },
  {
    subjectName: 'Databases',
    topicName: 'Transactions, Concurrency & Indexing',
    year: 2026,
    paper: 'GATE CSE 2026',
    questionNumber: 46,
    questionText: 'Which of the following concurrency control schedules is guaranteed to be conflict serializable?',
    options: [
      { key: 'A', text: 'Any schedule produced under Strict 2-Phase Locking (Strict 2PL)' },
      { key: 'B', text: 'Any schedule produced under Basic Timestamp Ordering' },
      { key: 'C', text: 'Any schedule that is view serializable' },
      { key: 'D', text: 'Any schedule that is recoverable' },
    ],
    correctAnswer: ['A', 'B'],
    questionType: 'MSQ',
    marks: 2,
    negativeMarks: 0,
    difficulty: 'hard',
    explanation: 'Strict 2PL and Timestamp Ordering both guarantee conflict serializability. View serializability is a superset and not always conflict serializable.',
  },
  {
    subjectName: 'Databases',
    topicName: 'Transactions, Concurrency & Indexing',
    year: 2023,
    paper: 'GATE CSE 2023',
    questionNumber: 47,
    questionText: 'A B+ tree index is constructed on an attribute of size 12 bytes. Disk block size is 1024 bytes and block pointers are 8 bytes. What is the maximum order (number of block pointers) of an internal node?',
    natRange: { min: 51, max: 51, exact: 51 },
    correctAnswer: 51,
    questionType: 'NAT',
    marks: 2,
    negativeMarks: 0,
    difficulty: 'hard',
    explanation: 'p * (pointer size) + (p-1) * (key size) <= Block Size => p * 8 + (p-1) * 12 <= 1024 => 20p - 12 <= 1024 => 20p <= 1036 => p = 51.',
  },

  // -------------------------------------------------------------
  // OPERATING SYSTEMS (OS) - 7 Unique Questions (11 Marks)
  // -------------------------------------------------------------
  {
    subjectName: 'Operating Systems',
    topicName: 'Deadlocks & Memory Management',
    year: 2025,
    paper: 'GATE CSE 2025 Set 1',
    questionNumber: 48,
    questionText: 'A system has 4 processes and 5 allocatable resources of the same type. What is the maximum number of resources that each process can request such that a deadlock is NEVER possible?',
    options: [
      { key: 'A', text: '1' },
      { key: 'B', text: '2' },
      { key: 'C', text: '3' },
      { key: 'D', text: '4' },
    ],
    correctAnswer: 'B',
    questionType: 'MCQ',
    marks: 1,
    negativeMarks: 0.33,
    difficulty: 'medium',
    explanation: 'Condition for no deadlock: 5 >= 4*(k-1) + 1 => 4 >= 4(k-1) => k <= 2.',
  },
  {
    subjectName: 'Operating Systems',
    topicName: 'File Systems & Storage',
    year: 2026,
    paper: 'GATE CSE 2026',
    questionNumber: 49,
    questionText: 'Which disk scheduling algorithm moves the disk arm back and forth across the disk surface, servicing requests in both directions?',
    options: [
      { key: 'A', text: 'SCAN (Elevator)' },
      { key: 'B', text: 'C-SCAN' },
      { key: 'C', text: 'FCFS' },
      { key: 'D', text: 'SSTF' },
    ],
    correctAnswer: 'A',
    questionType: 'MCQ',
    marks: 1,
    negativeMarks: 0.33,
    difficulty: 'easy',
    explanation: 'SCAN (Elevator algorithm) services requests in one direction until the end, then reverses direction servicing requests along the way.',
  },
  {
    subjectName: 'Operating Systems',
    topicName: 'CPU Scheduling & Process Synchronization',
    year: 2024,
    paper: 'GATE CSE 2024 Set 1',
    questionNumber: 50,
    questionText: 'Which of the following conditions must be satisfied by a valid solution to the Critical Section Problem?',
    options: [
      { key: 'A', text: 'Mutual Exclusion, Progress, and Bounded Waiting' },
      { key: 'B', text: 'Mutual Exclusion and Deadlock Avoidance only' },
      { key: 'C', text: 'Starvation Freedom and Preemption' },
      { key: 'D', text: 'Aging and Bounded Waiting' },
    ],
    correctAnswer: 'A',
    questionType: 'MCQ',
    marks: 1,
    negativeMarks: 0.33,
    difficulty: 'easy',
    explanation: 'The three mandatory criteria for the Critical Section Problem are Mutual Exclusion, Progress, and Bounded Waiting.',
  },
  {
    subjectName: 'Operating Systems',
    topicName: 'CPU Scheduling & Process Synchronization',
    year: 2026,
    paper: 'GATE CSE 2026',
    questionNumber: 51,
    questionText: 'Three processes P1, P2, and P3 arrive at time 0 with burst times 10 ms, 4 ms, and 2 ms respectively. If Round Robin scheduling with time quantum 2 ms is used, what is the average waiting time (in ms)?',
    natRange: { min: 5.33, max: 5.34, exact: 5.33 },
    correctAnswer: 5.33,
    questionType: 'NAT',
    marks: 2,
    negativeMarks: 0,
    difficulty: 'medium',
    explanation: 'CT: P3 = 6, P2 = 10, P1 = 16. WT: P1 = 6, P2 = 6, P3 = 4. Average WT = (6 + 6 + 4)/3 = 5.33 ms.',
  },
  {
    subjectName: 'Operating Systems',
    topicName: 'Deadlocks & Memory Management',
    year: 2024,
    paper: 'GATE CSE 2024 Set 2',
    questionNumber: 52,
    questionText: 'Consider a virtual memory system with a 32-bit logical address space and 4 KB page size. If each page table entry takes 4 bytes, what is the size of the single-level page table (in MB)?',
    natRange: { min: 4, max: 4, exact: 4 },
    correctAnswer: 4,
    questionType: 'NAT',
    marks: 2,
    negativeMarks: 0,
    difficulty: 'medium',
    explanation: 'Number of pages = 2^32 / 2^12 = 2^20 pages. Page Table Size = 2^20 * 4 bytes = 4 MB.',
  },
  {
    subjectName: 'Operating Systems',
    topicName: 'Deadlocks & Memory Management',
    year: 2025,
    paper: 'GATE CSE 2025 Set 2',
    questionNumber: 53,
    questionText: 'A system uses LRU page replacement algorithm with 3 physical frames. For the reference string: 1, 2, 3, 4, 1, 2, 5, 1, 2, 3, 4, 5 with initially empty frames, how many page faults occur?',
    natRange: { min: 10, max: 10, exact: 10 },
    correctAnswer: 10,
    questionType: 'NAT',
    marks: 2,
    negativeMarks: 0,
    difficulty: 'hard',
    explanation: 'Simulating LRU with 3 frames yields exactly 10 page faults.',
  },
  {
    subjectName: 'Operating Systems',
    topicName: 'File Systems & Storage',
    year: 2023,
    paper: 'GATE CSE 2023',
    questionNumber: 54,
    questionText: 'In a Unix-style file system, an inode has 10 direct block pointers, 1 single indirect pointer, and 1 double indirect pointer. Disk block size is 4 KB and disk block address takes 4 bytes. What is the maximum file size that can be represented (in MB)?',
    natRange: { min: 4100, max: 4101, exact: 4100 },
    correctAnswer: 4100,
    questionType: 'NAT',
    marks: 2,
    negativeMarks: 0,
    difficulty: 'hard',
    explanation: 'Direct = 10 * 4KB = 40 KB. Single indirect = 1024 * 4KB = 4 MB. Double indirect = 1024 * 1024 * 4KB = 4096 MB. Total = ~4100 MB.',
  },

  // -------------------------------------------------------------
  // COMPUTER NETWORKS (CN) - 7 Unique Questions (11 Marks)
  // -------------------------------------------------------------
  {
    subjectName: 'Computer Networks',
    topicName: 'IP Addressing & Subnetting',
    year: 2026,
    paper: 'GATE CSE 2026',
    questionNumber: 55,
    questionText: 'An organization is allocated the IP block 200.10.20.0/24. The administrator needs to divide it into 4 equal subnets. What is the subnet mask for each subnet?',
    options: [
      { key: 'A', text: '255.255.255.192' },
      { key: 'B', text: '255.255.255.224' },
      { key: 'C', text: '255.255.255.240' },
      { key: 'D', text: '255.255.255.128' },
    ],
    correctAnswer: 'A',
    questionType: 'MCQ',
    marks: 1,
    negativeMarks: 0.33,
    difficulty: 'easy',
    explanation: '4 subnets requires 2 bits: 24 + 2 = /26. Mask is 11000000 = 192 (255.255.255.192).',
  },
  {
    subjectName: 'Computer Networks',
    topicName: 'Transport & Data Link Protocols',
    year: 2024,
    paper: 'GATE CSE 2024 Set 1',
    questionNumber: 56,
    questionText: 'In a Go-Back-N ARQ sliding window protocol, sequence numbers are 4 bits wide. What is the maximum allowable sender window size?',
    natRange: { min: 15, max: 15, exact: 15 },
    correctAnswer: 15,
    questionType: 'NAT',
    marks: 1,
    negativeMarks: 0,
    difficulty: 'easy',
    explanation: 'Maximum sender window in GBN with k bits is 2^k - 1 = 2^4 - 1 = 15.',
  },
  {
    subjectName: 'Computer Networks',
    topicName: 'Routing Algorithms & Application Layer',
    year: 2025,
    paper: 'GATE CSE 2025 Set 2',
    questionNumber: 57,
    questionText: 'Which application layer protocol uses both TCP port 20 and TCP port 21?',
    options: [
      { key: 'A', text: 'FTP' },
      { key: 'B', text: 'HTTP' },
      { key: 'C', text: 'SMTP' },
      { key: 'D', text: 'DNS' },
    ],
    correctAnswer: 'A',
    questionType: 'MCQ',
    marks: 1,
    negativeMarks: 0.33,
    difficulty: 'easy',
    explanation: 'File Transfer Protocol (FTP) uses port 21 for control/commands and port 20 for data transfer.',
  },
  {
    subjectName: 'Computer Networks',
    topicName: 'Transport & Data Link Protocols',
    year: 2025,
    paper: 'GATE CSE 2025 Set 1',
    questionNumber: 58,
    questionText: 'A 100 km long link has a propagation speed of 2 * 10^8 m/s and bandwidth of 1 Gbps. What is the propagation delay (in microseconds)?',
    natRange: { min: 500, max: 500, exact: 500 },
    correctAnswer: 500,
    questionType: 'NAT',
    marks: 2,
    negativeMarks: 0,
    difficulty: 'medium',
    explanation: 'Propagation delay = Distance / Speed = (100 * 10^3 m) / (2 * 10^8 m/s) = 0.0005 s = 500 μs.',
  },
  {
    subjectName: 'Computer Networks',
    topicName: 'Transport & Data Link Protocols',
    year: 2026,
    paper: 'GATE CSE 2026',
    questionNumber: 59,
    questionText: 'A TCP connection is operating with Maximum Segment Size (MSS) of 1 KB. The congestion window is currently 16 KB and slow start threshold (ssthresh) is 8 KB. After 3 consecutive successful transmissions (with no packet loss), what is the new congestion window size (in KB)?',
    natRange: { min: 19, max: 19, exact: 19 },
    correctAnswer: 19,
    questionType: 'NAT',
    marks: 2,
    negativeMarks: 0,
    difficulty: 'medium',
    explanation: 'Since cwnd (16) > ssthresh (8), TCP is in Congestion Avoidance (additive increase: +1 KB per RTT). After 3 RTTs, cwnd = 16 + 3 = 19 KB.',
  },
  {
    subjectName: 'Computer Networks',
    topicName: 'Routing Algorithms & Application Layer',
    year: 2024,
    paper: 'GATE CSE 2024 Set 2',
    questionNumber: 60,
    questionText: 'Which of the following statements about Distance Vector and Link State routing algorithms is/are TRUE?',
    options: [
      { key: 'A', text: 'Distance Vector routing algorithm can suffer from the Count-to-Infinity problem.' },
      { key: 'B', text: 'Link State routing uses Dijkstra\'s algorithm to compute the shortest path tree.' },
      { key: 'C', text: 'OSPF is an Interior Gateway Protocol based on Link State routing.' },
      { key: 'D', text: 'RIP uses Link State routing with split horizon.' },
    ],
    correctAnswer: ['A', 'B', 'C'],
    questionType: 'MSQ',
    marks: 2,
    negativeMarks: 0,
    difficulty: 'hard',
    explanation: 'RIP uses Distance Vector routing (D is false). A, B, and C are correct statements.',
  },
  {
    subjectName: 'Computer Networks',
    topicName: 'Routing Algorithms & Application Layer',
    year: 2023,
    paper: 'GATE CSE 2023',
    questionNumber: 61,
    questionText: 'In an RSA cryptosystem, prime numbers are p = 3 and q = 11. If the public encryption key is e = 7, what is the private decryption key d?',
    natRange: { min: 3, max: 3, exact: 3 },
    correctAnswer: 3,
    questionType: 'NAT',
    marks: 2,
    negativeMarks: 0,
    difficulty: 'medium',
    explanation: 'n = 33, φ(n) = (3-1)(11-1) = 20. We need (e * d) mod 20 = 1 => (7 * d) mod 20 = 1 => 7 * 3 = 21 ≡ 1 mod 20 => d = 3.',
  },

  // -------------------------------------------------------------
  // DIGITAL LOGIC (DL) - 5 Unique Questions (7 Marks)
  // -------------------------------------------------------------
  {
    subjectName: 'Digital Logic',
    topicName: 'Combinational & Sequential Circuits',
    year: 2025,
    paper: 'GATE CSE 2025 Set 1',
    questionNumber: 62,
    questionText: 'How many 2-to-1 multiplexers are required to construct an 8-to-1 multiplexer?',
    natRange: { min: 7, max: 7, exact: 7 },
    correctAnswer: 7,
    questionType: 'NAT',
    marks: 1,
    negativeMarks: 0,
    difficulty: 'easy',
    explanation: 'Level 1 takes 4, Level 2 takes 2, Level 3 takes 1 -> Total = 4 + 2 + 1 = 7.',
  },
  {
    subjectName: 'Digital Logic',
    topicName: 'Number Representation & Logic Gates',
    year: 2026,
    paper: 'GATE CSE 2026',
    questionNumber: 63,
    questionText: 'What is the 8-bit 2\'s complement representation of the decimal number -37?',
    options: [
      { key: 'A', text: '11011011' },
      { key: 'B', text: '11011010' },
      { key: 'C', text: '10100101' },
      { key: 'D', text: '11100101' },
    ],
    correctAnswer: 'A',
    questionType: 'MCQ',
    marks: 1,
    negativeMarks: 0.33,
    difficulty: 'easy',
    explanation: '+37 is 00100101. 1s complement is 11011010. Adding 1 gives 11011011.',
  },
  {
    subjectName: 'Digital Logic',
    topicName: 'Combinational & Sequential Circuits',
    year: 2024,
    paper: 'GATE CSE 2024 Set 2',
    questionNumber: 64,
    questionText: 'A 4-bit synchronous binary counter uses flip-flops with clock-to-Q delay of 10 ns and AND gate delay of 5 ns. What is the maximum clock frequency (in MHz)?',
    natRange: { min: 66.6, max: 66.7, exact: 66.67 },
    correctAnswer: 66.67,
    questionType: 'NAT',
    marks: 1,
    negativeMarks: 0,
    difficulty: 'medium',
    explanation: 'T_min = 10 + 5 = 15 ns. f_max = 1 / 15 ns = 66.67 MHz.',
  },
  {
    subjectName: 'Digital Logic',
    topicName: 'Combinational & Sequential Circuits',
    year: 2025,
    paper: 'GATE CSE 2025 Set 2',
    questionNumber: 65,
    questionText: 'Consider the Boolean function F(A, B, C, D) = Σ m(0, 2, 5, 7, 8, 10, 13, 15). What is the minimal number of essential prime implicants of F?',
    natRange: { min: 2, max: 2, exact: 2 },
    correctAnswer: 2,
    questionType: 'NAT',
    marks: 2,
    negativeMarks: 0,
    difficulty: 'medium',
    explanation: 'K-map simplification yields 2 essential prime implicants: B\'D\' and BD (Total = 2).',
  },
  {
    subjectName: 'Digital Logic',
    topicName: 'Number Representation & Logic Gates',
    year: 2023,
    paper: 'GATE CSE 2023',
    questionNumber: 66,
    questionText: 'In standard IEEE 754 single-precision 32-bit floating point format, what is the bias for the 8-bit exponent?',
    natRange: { min: 127, max: 127, exact: 127 },
    correctAnswer: 127,
    questionType: 'NAT',
    marks: 2,
    negativeMarks: 0,
    difficulty: 'easy',
    explanation: 'For k = 8 bits, Bias = 2^(k-1) - 1 = 2^7 - 1 = 127.',
  },

  // -------------------------------------------------------------
  // COMPUTER ORGANIZATION & ARCHITECTURE (COA) - 6 Unique Questions (10 Marks)
  // -------------------------------------------------------------
  {
    subjectName: 'Computer Organization and Architecture',
    topicName: 'Pipelining & Hazards',
    year: 2025,
    paper: 'GATE CSE 2025 Set 2',
    questionNumber: 67,
    questionText: 'A 5-stage pipelined processor has stage delays of 150 ps, 120 ps, 160 ps, 140 ps, and 110 ps. The pipeline register delay is 20 ps. What is the clock cycle time of the processor (in ps)?',
    natRange: { min: 180, max: 180, exact: 180 },
    correctAnswer: 180,
    questionType: 'NAT',
    marks: 1,
    negativeMarks: 0,
    difficulty: 'easy',
    explanation: 'Clock cycle time = Max(stage delays) + register delay = 160 ps + 20 ps = 180 ps.',
  },
  {
    subjectName: 'Computer Organization and Architecture',
    topicName: 'Instruction Formats & Addressing Modes',
    year: 2026,
    paper: 'GATE CSE 2026',
    questionNumber: 68,
    questionText: 'Which addressing mode is best suited for accessing elements in a one-dimensional contiguous array in a loop?',
    options: [
      { key: 'A', text: 'Base Indexed / Auto-Increment Mode' },
      { key: 'B', text: 'Immediate Addressing Mode' },
      { key: 'C', text: 'Direct Absolute Addressing Mode' },
      { key: 'D', text: 'Relative Addressing Mode' },
    ],
    correctAnswer: 'A',
    questionType: 'MCQ',
    marks: 1,
    negativeMarks: 0.33,
    difficulty: 'easy',
    explanation: 'Base indexed and auto-increment addressing modes allow stepping through array elements with minimal instruction overhead.',
  },
  {
    subjectName: 'Computer Organization and Architecture',
    topicName: 'Memory Hierarchy & Cache Mapping',
    year: 2026,
    paper: 'GATE CSE 2026',
    questionNumber: 69,
    questionText: 'In a 2-level memory system, the cache hit ratio is 0.9. Cache access time is 2 ns and main memory access time is 50 ns. What is the Average Memory Access Time (AMAT) in ns?',
    natRange: { min: 7, max: 7, exact: 7 },
    correctAnswer: 7,
    questionType: 'NAT',
    marks: 2,
    negativeMarks: 0,
    difficulty: 'easy',
    explanation: 'AMAT = Hit Time + (Miss Rate * Miss Penalty) = 2 + (0.1 * 50) = 7 ns.',
  },
  {
    subjectName: 'Computer Organization and Architecture',
    topicName: 'Memory Hierarchy & Cache Mapping',
    year: 2024,
    paper: 'GATE CSE 2024 Set 1',
    questionNumber: 70,
    questionText: 'A 4-way set associative cache memory has total size of 64 KB with block size of 32 bytes. The CPU generates 32-bit byte physical addresses. How many bits are there in the TAG field?',
    natRange: { min: 18, max: 18, exact: 18 },
    correctAnswer: 18,
    questionType: 'NAT',
    marks: 2,
    negativeMarks: 0,
    difficulty: 'medium',
    explanation: 'Total blocks = 64 KB / 32 B = 2048 blocks. Sets = 2048 / 4 = 512 = 2^9 (9 set bits). Offset = 32 B = 2^5 (5 offset bits). Tag bits = 32 - 9 - 5 = 18 bits.',
  },
  {
    subjectName: 'Computer Organization and Architecture',
    topicName: 'Pipelining & Hazards',
    year: 2025,
    paper: 'GATE CSE 2025 Set 1',
    questionNumber: 71,
    questionText: 'A non-pipelined processor takes 50 ns to execute an instruction. A 5-stage pipelined version of the processor has a clock cycle time of 11 ns. What is the ideal speedup achieved by the pipeline for a large number of instructions?',
    natRange: { min: 4.54, max: 4.55, exact: 4.55 },
    correctAnswer: 4.55,
    questionType: 'NAT',
    marks: 2,
    negativeMarks: 0,
    difficulty: 'medium',
    explanation: 'Ideal speedup = Time_nonpipelined / Clock_pipelined = 50 / 11 ≈ 4.55.',
  },
  {
    subjectName: 'Computer Organization and Architecture',
    topicName: 'Instruction Formats & Addressing Modes',
    year: 2023,
    paper: 'GATE CSE 2023',
    questionNumber: 72,
    questionText: 'A CPU has 24-bit instructions and 32 general-purpose registers (R0 to R31). If an instruction format supports 2 register operands and a 10-bit immediate constant, what is the maximum number of distinct opcodes that can be supported?',
    natRange: { min: 16, max: 16, exact: 16 },
    correctAnswer: 16,
    questionType: 'NAT',
    marks: 2,
    negativeMarks: 0,
    difficulty: 'medium',
    explanation: 'Each register needs log2(32) = 5 bits. Total operand bits = 5 + 5 + 10 = 20 bits. Opcode bits = 24 - 20 = 4 bits => 2^4 = 16 distinct opcodes.',
  },

  // -------------------------------------------------------------
  // COMPILER DESIGN (CD) - 5 Unique Questions (8 Marks)
  // -------------------------------------------------------------
  {
    subjectName: 'Compiler Design',
    topicName: 'Lexical Analysis & Parsing',
    year: 2026,
    paper: 'GATE CSE 2026',
    questionNumber: 73,
    questionText: 'Which parser generator construct produces the largest parsing table for the same context-free grammar?',
    options: [
      { key: 'A', text: 'Canonical LR (CLR(1))' },
      { key: 'B', text: 'LALR(1)' },
      { key: 'C', text: 'SLR(1)' },
      { key: 'D', text: 'LR(0)' },
    ],
    correctAnswer: 'A',
    questionType: 'MCQ',
    marks: 1,
    negativeMarks: 0.33,
    difficulty: 'easy',
    explanation: 'CLR(1) has states split by lookaheads and generates far more states than LALR(1), SLR(1), or LR(0).',
  },
  {
    subjectName: 'Compiler Design',
    topicName: 'Code Optimization & Runtime Environments',
    year: 2025,
    paper: 'GATE CSE 2025 Set 1',
    questionNumber: 74,
    questionText: 'Which compiler optimization technique eliminates operations that compute values already computed in preceding code blocks without intermediate changes?',
    options: [
      { key: 'A', text: 'Common Subexpression Elimination' },
      { key: 'B', text: 'Loop Unrolling' },
      { key: 'C', text: 'Register Allocation' },
      { key: 'D', text: 'Strength Reduction' },
    ],
    correctAnswer: 'A',
    questionType: 'MCQ',
    marks: 1,
    negativeMarks: 0.33,
    difficulty: 'easy',
    explanation: 'Common Subexpression Elimination identifies identical expressions and reuses previously computed values.',
  },
  {
    subjectName: 'Compiler Design',
    topicName: 'Lexical Analysis & Parsing',
    year: 2025,
    paper: 'GATE CSE 2025 Set 2',
    questionNumber: 75,
    questionText: 'Consider the grammar:\nS -> A a | b A c | d c | b d a\nA -> d\nWhat is the status of this grammar with respect to LL(1) and LR(1)?',
    options: [
      { key: 'A', text: 'It is LR(1) but NOT LL(1)' },
      { key: 'B', text: 'It is LL(1) but NOT LR(1)' },
      { key: 'C', text: 'It is both LL(1) and LR(1)' },
      { key: 'D', text: 'It is neither LL(1) nor LR(1)' },
    ],
    correctAnswer: 'A',
    questionType: 'MCQ',
    marks: 2,
    negativeMarks: 0.66,
    difficulty: 'medium',
    explanation: 'It has FIRST/FIRST conflict on \'b\' and \'d\' for LL(1) parsing, but LR(1) lookahead correctly distinguishes the handles.',
  },
  {
    subjectName: 'Compiler Design',
    topicName: 'Syntax-Directed Translation & Intermediate Code',
    year: 2024,
    paper: 'GATE CSE 2024 Set 2',
    questionNumber: 76,
    questionText: 'Which of the following statements about Syntax Directed Translations (SDT) is/are TRUE?',
    options: [
      { key: 'A', text: 'An S-attributed definition can be evaluated during bottom-up parsing using an LR parser.' },
      { key: 'B', text: 'Every S-attributed definition is also an L-attributed definition.' },
      { key: 'C', text: 'Synthesized attributes can only be computed from children node attributes.' },
      { key: 'D', text: 'Inherited attributes can never be used in top-down LL(1) parsers.' },
    ],
    correctAnswer: ['A', 'B', 'C'],
    questionType: 'MSQ',
    marks: 2,
    negativeMarks: 0,
    difficulty: 'hard',
    explanation: 'A, B, and C are correct. D is false because L-attributed SDTs can evaluate inherited attributes in top-down parsers.',
  },
  {
    subjectName: 'Compiler Design',
    topicName: 'Code Optimization & Runtime Environments',
    year: 2023,
    paper: 'GATE CSE 2023',
    questionNumber: 77,
    questionText: 'Replacing an expensive multiplication operation `x = i * 8` with a faster bitwise left shift `x = i << 3` is an example of which compiler optimization?',
    options: [
      { key: 'A', text: 'Strength Reduction' },
      { key: 'B', text: 'Constant Folding' },
      { key: 'C', text: 'Dead Code Elimination' },
      { key: 'D', text: 'Loop Jamming' },
    ],
    correctAnswer: 'A',
    questionType: 'MCQ',
    marks: 2,
    negativeMarks: 0.66,
    difficulty: 'easy',
    explanation: 'Strength reduction replaces computationally heavy operations with lighter equivalent operations.',
  },
];
